<?php
declare(strict_types=1);

return [
    'version' => '2026.08.13',
    'profiles' => [
        'Desenvolvedor' => 'Aqui você administra usuários, acompanha solicitações, consulta registros técnicos e mantém salas e itens.',
        'Técnico' => 'Aqui você cadastra e mantém as salas e os itens controlados pelo sistema.',
        'Tecnico' => 'Aqui você cadastra e mantém as salas e os itens controlados pelo sistema.',
        'Administrativo' => 'Aqui você acompanha reservas, disponibilidade, chaves e retiradas administrativas.',
        'Diretor' => 'Aqui você acompanha indicadores, relatórios, reservas, disponibilidade, chaves e movimentações da unidade.',
        'Secretário de Curso' => 'Aqui você organiza cursos, períodos, reservas acadêmicas e retiradas autorizadas.',
        'Coordenador de Curso' => 'Aqui você gerencia matérias e reservas de aulas vinculadas ao curso.',
        'Agente de Portaria' => 'Aqui você mantém salas e itens, registra retiradas e devoluções, cria autorizações e acompanha o histórico.',
        'Professor' => 'Aqui você consulta salas, solicita reservas, acompanha aulas, bolsistas e retiradas.',
        'Aluno Bolsista' => 'Aqui você consulta suas informações e retira somente recursos previamente autorizados.',
        'Estagiario' => 'Aqui você consulta suas informações e retira somente recursos previamente autorizados.',
        'Estagiário' => 'Aqui você consulta suas informações e retira somente recursos previamente autorizados.',
        'Aluno' => 'Aqui você consulta a situação das salas e os recursos liberados para o seu usuário.',
        'Visitante' => 'Aqui você consulta as salas e retira somente a chave autorizada para a sua visita.',
        'Motorista' => 'Aqui você consulta as salas e retira somente as chaves que foram autorizadas para o seu usuário.',
        'Serviços Gerais' => 'Aqui você consulta ambientes e registra a retirada dos recursos necessários ao serviço.',
    ],
    'paths' => [
        '/desenvolvedor' => ['Visão geral', 'Veja os atalhos e os principais dados administrativos do SGRP.'],
        '/desenvolvedor/usuarios' => ['Usuários', 'Cadastre, edite, desative e consulte as contas que utilizam o sistema.'],
        '/desenvolvedor/usuarios/solicitacoes' => ['Solicitações', 'Analise os cadastros recebidos pelo Google Forms e aprove ou recuse cada pedido.'],
        '/desenvolvedor/logs' => ['Logs', 'Consulte registros técnicos para investigar erros e comportamentos inesperados.'],
        '/desenvolvedor/vinculos-bolsistas' => ['Vínculos', 'Acompanhe os vínculos entre professores e alunos bolsistas.'],
        '/desenvolvedor/advertencias' => ['Advertências', 'Consulte advertências e bloqueios relacionados à retirada de chaves.'],

        '/administrativo' => ['Visão administrativa', 'Acesse o resumo das atividades e recursos administrados pelo setor.'],
        '/administrativo/reservas-salas' => ['Reservas', 'Cadastre e acompanhe reservas de salas para atividades institucionais.'],
        '/administrativo/retiradas' => ['Retiradas', 'Registre a retirada de chaves e itens disponíveis para o setor.'],
        '/administrativo/disponibilidade-salas' => ['Disponibilidade', 'Pesquise quais salas estão livres, reservadas ou com a chave retirada.'],
        '/administrativo/chaves-autorizadas' => ['Autorizações de chaves', 'Libere uma sala específica ou acesso total para um usuário, com validade e dias permitidos.'],

        '/diretor' => ['Visão da direção', 'Veja um resumo rápido da ocupação e das atividades da unidade.'],
        '/diretor/chaves' => ['Chaves', 'Consulte e registre retiradas de chaves disponíveis.'],
        '/diretor/reservas' => ['Reservas', 'Acompanhe e altere a situação das solicitações de reserva.'],
        '/diretor/movimentacoes' => ['Movimentações', 'Consulte retiradas e devoluções registradas no sistema.'],
        '/diretor/relatorios' => ['Relatórios da Direção', 'Analise indicadores, acessos por perfil, evolução e histórico diário, semanal ou mensal, com pesquisa por autocomplete e exportação.'],
        '/diretor/disponibilidade' => ['Disponibilidade', 'Pesquise a situação das salas por data e horário.'],

        '/secretario' => ['Visão da secretaria', 'Veja os atalhos das rotinas acadêmicas da secretaria.'],
        '/secretario/cursos' => ['Cursos', 'Cadastre e atualize os cursos atendidos pela secretaria.'],
        '/secretario/periodos-academicos' => ['Períodos acadêmicos', 'Organize os períodos usados nas reservas e atividades acadêmicas.'],
        '/secretario/reservas-curso' => ['Reservas do curso', 'Registre e acompanhe reservas relacionadas aos cursos.'],
        '/secretario/retirada-chaves' => ['Retiradas', 'Retire chaves e itens disponíveis para a secretaria.'],

        '/coordenador' => ['Visão da coordenação', 'Veja os atalhos das atividades sob responsabilidade da coordenação.'],
        '/coordenador/materias' => ['Matérias', 'Cadastre e organize as disciplinas vinculadas ao curso.'],
        '/coordenador/reservas-aulas' => ['Reservas de aulas', 'Organize salas e horários usados pelas aulas do curso.'],

        '/portaria' => ['Visão da portaria', 'Veja rapidamente retiradas abertas e atividades que exigem atenção.'],
        '/portaria/salas' => ['Cadastro de salas', 'Cadastre ambientes e mantenha seus dados e sua situação atualizados.'],
        '/portaria/itens' => ['Cadastro de itens', 'Cadastre e acompanhe os objetos controlados pela Portaria.'],
        '/portaria/retiradas' => ['Retiradas e devoluções', 'Registre quem retirou uma chave ou item e confirme sua devolução.'],
        '/portaria/reservas' => ['Reservas', 'Cadastre uma reserva para solicitante autorizado ou informe o nome de uma pessoa sem cadastro.'],
        '/portaria/vinculos-bolsistas' => ['Vínculos', 'Consulte os bolsistas e seus respectivos professores responsáveis.'],
        '/portaria/permissoes' => ['Permissões', 'Autorize uma ou várias salas por vez e escolha uma validade ou a opção Nunca expirar.'],
        '/portaria/visitantes' => ['Visitantes', 'Cadastre acessos temporários com data automática de expiração.'],
        '/portaria/salas-hoje' => ['Salas hoje', 'Veja a situação atual dos ambientes para orientar o atendimento.'],
        '/portaria/historico' => ['Histórico', 'Consulte movimentações anteriores e identifique responsáveis e horários.'],
        '/portaria/relatorio-movimentacoes' => ['Imprimir movimentações', 'Escolha a data, o intervalo de horas e uma sala para gerar e imprimir o relatório da Portaria.'],

        '/professor' => ['Visão do professor', 'Veja seus principais atalhos e informações acadêmicas.'],
        '/professor/disponibilidade-salas' => ['Disponibilidade', 'Pesquise uma sala livre antes de solicitar uma reserva.'],
        '/professor/reservas-salas' => ['Reservas', 'Solicite e acompanhe suas reservas de salas.'],
        '/professor/aulas-semestre' => ['Aulas', 'Consulte as aulas e os horários registrados para o semestre.'],
        '/professor/orientandos-bolsistas' => ['Bolsistas', 'Cadastre orientandos e autorize as chaves necessárias às atividades.'],
        '/professor/retiradas' => ['Retiradas', 'Retire chaves e itens disponíveis para o seu usuário.'],

        '/bolsista' => ['Área do bolsista', 'Consulte as informações relacionadas ao seu vínculo e projeto.'],
        '/bolsista/retiradas' => ['Retiradas autorizadas', 'Veja e retire somente chaves e itens que foram liberados para você.'],
        '/aluno' => ['Área do aluno', 'Acesse os recursos de consulta disponíveis para alunos.'],
        '/aluno/consulta-salas' => ['Consulta de salas', 'Pesquise a situação de cada sala por data, horário, nome ou código.'],
        '/retiradas-autorizadas' => ['Chaves autorizadas', 'Esta área aparece quando uma chave é liberada especificamente para o seu usuário.'],
        '/visitante' => ['Área do visitante', 'Consulte a situação dos ambientes disponíveis no sistema.'],
        '/visitante/chave' => ['Chave autorizada', 'Veja e retire somente a chave liberada para a sua visita.'],
        '/motorista' => ['Consulta de salas', 'Pesquise a situação de todas as salas por data, horário, nome ou código.'],
        '/motorista/retiradas' => ['Chaves autorizadas', 'Veja e retire somente as chaves que a Portaria ou o setor Administrativo liberou para você.'],
        '/servicos-gerais' => ['Área de Serviços Gerais', 'Consulte a situação dos ambientes antes de iniciar o atendimento.'],
        '/servicos-gerais/retiradas' => ['Retiradas', 'Registre a retirada das chaves e dos itens necessários ao serviço.'],

        '/perfil' => ['Meu perfil', 'Atualize seu nome, sua foto e sua senha de acesso.'],
        '/calendario-salas' => ['Calendário de salas', 'Visualize por mês as reservas, aulas e retiradas de chave de cada sala.'],
        '/salas/detalhes' => ['Detalhes da sala', 'Consulte identificação, situação e a agenda mensal com reservas, aulas e retiradas de chave.'],
        '/salas/atividade' => ['Detalhes da atividade', 'Veja todas as informações da reserva, aula ou retirada de chave selecionada no calendário.'],
        '/usuarios/cadastro' => ['Cadastrar usuário', 'Crie uma conta e defina o perfil e os vínculos necessários.'],
        '/usuarios/editar' => ['Editar usuário', 'Atualize dados, perfil, vínculos, senha e situação de uma conta.'],
        '/bolsista/sala-pesquisa' => ['Retirada autorizada', 'Consulte os dados do vínculo e retire a chave liberada para a atividade.'],
        '/coordenador/chaves-autorizadas' => ['Chaves autorizadas', 'Consulte os acessos vinculados às atividades do curso.'],
    ],
    'details' => [
        '/desenvolvedor' => ['category' => 'Visão geral', 'functions' => ['Consultar indicadores do sistema', 'Abrir qualquer módulo disponível']],
        '/desenvolvedor/usuarios' => ['category' => 'Usuários e acessos', 'functions' => ['Listar usuários', 'Cadastrar usuário', 'Editar conta', 'Excluir acesso', 'Abrir solicitações']],
        '/desenvolvedor/usuarios/solicitacoes' => ['category' => 'Usuários e acessos', 'functions' => ['Analisar cadastros do formulário', 'Aprovar solicitação', 'Recusar solicitação', 'Limpar solicitações analisadas']],
        '/desenvolvedor/logs' => ['category' => 'Auditoria e segurança', 'functions' => ['Consultar registros técnicos', 'Filtrar ocorrências', 'Limpar registros antigos']],
        '/desenvolvedor/vinculos-bolsistas' => ['category' => 'Usuários e acessos', 'functions' => ['Consultar vínculos', 'Vincular bolsista e professor', 'Atualizar o vínculo acadêmico']],
        '/desenvolvedor/advertencias' => ['category' => 'Auditoria e segurança', 'functions' => ['Configurar regras de advertência', 'Consultar bloqueios', 'Atualizar bloqueio', 'Excluir bloqueio']],

        '/administrativo' => ['category' => 'Visão geral', 'functions' => ['Consultar atalhos administrativos', 'Abrir reservas, disponibilidade e chaves']],
        '/administrativo/reservas-salas' => ['category' => 'Salas e reservas', 'functions' => ['Solicitar reserva', 'Escolher sala e período', 'Acompanhar reservas cadastradas']],
        '/administrativo/retiradas' => ['category' => 'Chaves e retiradas', 'functions' => ['Consultar chaves disponíveis', 'Retirar chave', 'Consultar itens disponíveis', 'Retirar item']],
        '/administrativo/disponibilidade-salas' => ['category' => 'Salas e reservas', 'functions' => ['Pesquisar por nome ou código', 'Filtrar status, tipo, data e horário', 'Ver detalhes da sala', 'Solicitar sala']],
        '/administrativo/chaves-autorizadas' => ['category' => 'Chaves e retiradas', 'functions' => ['Autorizar uma chave ou todas as chaves', 'Definir validade e dias permitidos', 'Editar autorização', 'Revogar autorização']],

        '/diretor' => ['category' => 'Visão geral', 'functions' => ['Consultar resumo de hoje, da semana e do mês', 'Acompanhar pendências de devolução', 'Abrir relatórios, chaves, reservas e disponibilidade']],
        '/diretor/chaves' => ['category' => 'Chaves e retiradas', 'functions' => ['Consultar chaves disponíveis', 'Confirmar a senha', 'Registrar retirada de chave']],
        '/diretor/reservas' => ['category' => 'Salas e reservas', 'functions' => ['Consultar reservas', 'Analisar informações', 'Atualizar situação da reserva']],
        '/diretor/movimentacoes' => ['category' => 'Consultas e histórico', 'functions' => ['Consultar retiradas e devoluções', 'Identificar usuário, recurso e horários']],
        '/diretor/relatorios' => ['category' => 'Relatórios executivos', 'functions' => ['Alternar entre visão diária, semanal e mensal', 'Pesquisar com autocomplete de usuários, salas, itens e códigos', 'Filtrar por recurso, situação e movimentação', 'Consultar indicadores e o gráfico de acessos por perfil', 'Acompanhar a evolução e os rankings do período', 'Ver o histórico detalhado', 'Exportar todos os registros filtrados em CSV']],
        '/diretor/disponibilidade' => ['category' => 'Salas e reservas', 'functions' => ['Pesquisar salas', 'Filtrar data e horário', 'Ver situação e detalhes']],

        '/secretario' => ['category' => 'Visão geral', 'functions' => ['Consultar atalhos acadêmicos', 'Abrir cursos, períodos e reservas']],
        '/secretario/cursos' => ['category' => 'Cadastros acadêmicos', 'functions' => ['Criar curso', 'Editar curso', 'Excluir ou inativar curso']],
        '/secretario/periodos-academicos' => ['category' => 'Cadastros acadêmicos', 'functions' => ['Criar período acadêmico', 'Editar datas', 'Alterar situação', 'Excluir ou inativar período']],
        '/secretario/reservas-curso' => ['category' => 'Salas e reservas', 'functions' => ['Solicitar reserva do curso', 'Definir sala, atividade e período', 'Acompanhar solicitações']],
        '/secretario/retirada-chaves' => ['category' => 'Chaves e retiradas', 'functions' => ['Consultar chaves disponíveis', 'Retirar chave', 'Consultar itens', 'Retirar item']],

        '/coordenador' => ['category' => 'Visão geral', 'functions' => ['Consultar atalhos do curso', 'Abrir matérias e reservas de aulas']],
        '/coordenador/materias' => ['category' => 'Cadastros acadêmicos', 'functions' => ['Cadastrar disciplina', 'Editar disciplina', 'Excluir disciplina']],
        '/coordenador/reservas-aulas' => ['category' => 'Salas e reservas', 'functions' => ['Cadastrar reserva recorrente de aula', 'Editar horários e sala', 'Excluir reserva de aula']],

        '/portaria' => ['category' => 'Visão geral', 'functions' => ['Consultar retiradas em aberto', 'Acompanhar ocorrências que exigem atenção', 'Abrir rotinas da portaria']],
        '/portaria/salas' => ['category' => 'Cadastros', 'functions' => ['Cadastrar sala', 'Editar sala', 'Alterar situação', 'Excluir ou bloquear sala']],
        '/portaria/itens' => ['category' => 'Cadastros', 'functions' => ['Cadastrar item', 'Editar item', 'Alterar disponibilidade', 'Excluir ou indisponibilizar item']],
        '/portaria/retiradas' => ['category' => 'Chaves e retiradas', 'functions' => ['Registrar retirada para um usuário', 'Confirmar devolução de chave', 'Confirmar devolução de item', 'Registrar observação']],
        '/portaria/reservas' => ['category' => 'Salas e reservas', 'functions' => ['Selecionar um solicitante autorizado', 'Informar o nome de uma pessoa sem cadastro', 'Cadastrar reserva', 'Editar reserva', 'Consultar situação', 'Excluir registro do histórico']],
        '/portaria/vinculos-bolsistas' => ['category' => 'Usuários e acessos', 'functions' => ['Consultar vínculos de bolsistas', 'Vincular bolsista e professor responsável']],
        '/portaria/permissoes' => ['category' => 'Usuários e acessos', 'functions' => ['Filtrar permissões por usuário', 'Autorizar várias salas de uma vez', 'Criar acesso sem expiração', 'Editar sala, validade, dias e situação', 'Revogar e remover autorização da lista', 'Consultar permissões de itens']],
        '/portaria/visitantes' => ['category' => 'Usuários e acessos', 'functions' => ['Cadastrar visitante com validade', 'Editar dados, expiração e situação', 'Excluir acesso de visitante', 'Expirar acessos automaticamente']],
        '/portaria/salas-hoje' => ['category' => 'Consultas e histórico', 'functions' => ['Consultar situação das salas hoje', 'Identificar reservas e chaves retiradas']],
        '/portaria/historico' => ['category' => 'Consultas e histórico', 'functions' => ['Filtrar movimentações', 'Consultar responsáveis', 'Ver retiradas, devoluções e observações']],
        '/portaria/relatorio-movimentacoes' => ['category' => 'Consultas e histórico', 'functions' => ['Escolher a data do relatório', 'Definir hora inicial e hora final', 'Filtrar uma sala ou todas as salas', 'Consultar retiradas e devoluções do período', 'Imprimir o relatório completo']],

        '/professor' => ['category' => 'Visão geral', 'functions' => ['Consultar atalhos acadêmicos', 'Abrir reservas, aulas, bolsistas e retiradas']],
        '/professor/disponibilidade-salas' => ['category' => 'Salas e reservas', 'functions' => ['Pesquisar salas livres', 'Filtrar data e horário', 'Ver detalhes', 'Solicitar sala']],
        '/professor/reservas-salas' => ['category' => 'Salas e reservas', 'functions' => ['Solicitar reserva', 'Acompanhar situação', 'Editar solicitação', 'Excluir reserva']],
        '/professor/aulas-semestre' => ['category' => 'Consultas e histórico', 'functions' => ['Consultar disciplina, sala e turma', 'Ver dia e horário das aulas']],
        '/professor/orientandos-bolsistas' => ['category' => 'Usuários e acessos', 'functions' => ['Cadastrar bolsista', 'Gerar e copiar senha', 'Editar orientando', 'Liberar chave', 'Excluir vínculo']],
        '/professor/retiradas' => ['category' => 'Chaves e retiradas', 'functions' => ['Consultar chaves autorizadas', 'Retirar chave', 'Consultar itens', 'Retirar item']],

        '/bolsista' => ['category' => 'Visão geral', 'functions' => ['Consultar vínculo, projeto e professor', 'Abrir retiradas autorizadas']],
        '/bolsista/retiradas' => ['category' => 'Chaves e retiradas', 'functions' => ['Consultar recursos autorizados', 'Confirmar a senha', 'Retirar chave', 'Retirar item']],
        '/bolsista/sala-pesquisa' => ['category' => 'Chaves e retiradas', 'functions' => ['Consultar dados do vínculo', 'Ver chave autorizada', 'Confirmar a senha e retirar']],
        '/aluno' => ['category' => 'Visão geral', 'functions' => ['Consultar atalhos disponíveis', 'Abrir consulta de salas']],
        '/aluno/consulta-salas' => ['category' => 'Salas e reservas', 'functions' => ['Pesquisar sala', 'Filtrar status, tipo, data e horário', 'Ver detalhes da sala']],
        '/retiradas-autorizadas' => ['category' => 'Chaves e retiradas', 'functions' => ['Consultar chaves liberadas', 'Confirmar a senha', 'Registrar retirada autorizada']],
        '/visitante' => ['category' => 'Salas e reservas', 'functions' => ['Pesquisar salas', 'Consultar status e detalhes dos ambientes']],
        '/visitante/chave' => ['category' => 'Chaves e retiradas', 'functions' => ['Consultar chave autorizada', 'Confirmar a senha', 'Registrar retirada']],
        '/motorista' => ['category' => 'Salas e reservas', 'functions' => ['Pesquisar salas', 'Filtrar status, tipo, data e horário', 'Ver detalhes dos ambientes']],
        '/motorista/retiradas' => ['category' => 'Chaves e retiradas', 'functions' => ['Consultar chaves autorizadas', 'Confirmar a senha', 'Registrar retirada']],
        '/servicos-gerais' => ['category' => 'Salas e reservas', 'functions' => ['Pesquisar ambientes', 'Consultar situação e detalhes']],
        '/servicos-gerais/retiradas' => ['category' => 'Chaves e retiradas', 'functions' => ['Consultar chaves e itens', 'Confirmar a senha', 'Retirar chave', 'Retirar item']],

        '/perfil' => ['category' => 'Minha conta', 'functions' => ['Alterar foto', 'Atualizar nome', 'Trocar senha', 'Salvar dados']],
        '/calendario-salas' => ['category' => 'Salas e reservas', 'functions' => ['Visualizar o mês completo', 'Navegar entre meses', 'Voltar para o mês atual', 'Filtrar por sala', 'Distinguir reservas, aulas e retiradas de chave', 'Abrir o calendário da sala']],
        '/salas/detalhes' => ['category' => 'Salas e reservas', 'functions' => ['Consultar código, bloco e situação', 'Navegar pela agenda mensal', 'Consultar reservas e aulas por dia', 'Ver quem retirou a chave e o horário']],
        '/salas/atividade' => ['category' => 'Salas e reservas', 'functions' => ['Ver informações completas sem cortes', 'Identificar sala e responsáveis', 'Consultar datas, horários e situação', 'Voltar ao mesmo mês do calendário']],
        '/usuarios/cadastro' => ['category' => 'Usuários e acessos', 'functions' => ['Informar dados pessoais', 'Definir perfil e vínculos', 'Criar senha', 'Salvar usuário']],
        '/usuarios/editar' => ['category' => 'Usuários e acessos', 'functions' => ['Atualizar dados pessoais', 'Alterar perfil e vínculos', 'Redefinir senha', 'Ativar ou desativar conta']],
        '/coordenador/chaves-autorizadas' => ['category' => 'Chaves e retiradas', 'functions' => ['Consultar chaves vinculadas ao curso']],
    ],
];
